version: "3.9"

services:
  traefik-proxy:
    extends:
      file: docker-compose.base.yml
      service: traefik-proxy
    ports:
      - '0.0.0.0:9900:9900'
      - '0.0.0.0:9901:9901'

  traefik-hub:
    container_name: traefik-hub-agent
    image: ghcr.io/traefik/hub-agent-traefik:v0.7.2
    restart: always
    command:
      - run
      - --hub.token=${TRAEFIK_HUB_CODE}
      - --auth-server.advertise-url=http://traefik-hub-agent
      - --traefik.host=traefik-proxy
      - --traefik.tls.insecure=true
    depends_on:
      - traefik-proxy
    networks:
      - traefik-internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  socket-proxy:
    extends:
      file: docker-compose.base.yml
      service: socket-proxy

  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb

  authelia:
    extends:
      file: docker-compose.base.yml
      service: authelia

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis


#-----------
# Networks
#-----------
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge

#-----------
# Secrets
#-----------
secrets:
  authelia_jwt_secret:
    file: ./secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ./secrets/authelia_session_secret
  authelia_notifier_smtp_password:
    file: ./secrets/authelia_notifier_smtp_password
  authelia_storage_encryption_key:
    file: ./secrets/authelia_storage_encryption_key
  authelia_hmac_secret:
    file: ./secrets/authelia_hmac_secret
  authelia_oidc_issuer_private_key:
    file: ./secrets/authelia_oidc_issuer_private_key
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
