version: "3.9"

services:
  traefik-proxy:
    extends:
      file: docker-compose.base.yml
      service: traefik-proxy
    environment:
      CF_API_EMAIL_FILE: '/run/secrets/cf_email' # Uncomment for Cloudflare support
      CF_API_KEY_FILE: '/run/secrets/cf_api_key' # Uncomment for Cloudflare support
    secrets:
      - cf_email
      - cf_api_key

  socket-proxy:
    extends:
      file: docker-compose.base.yml
      service: socket-proxy

  mariadb:
    extends:
      file: docker-compose.base.yml
      service: mariadb

  authelia:
    extends:
      file: docker-compose.base.yml
      service: authelia

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

#-----------
# Networks
#-----------
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge

#-----------
# Secrets
#-----------
secrets:
  authelia_jwt_secret:
    file: ./secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ./secrets/authelia_session_secret
  authelia_notifier_smtp_password:
    file: ./secrets/authelia_notifier_smtp_password
  authelia_storage_encryption_key:
    file: ./secrets/authelia_storage_encryption_key
  authelia_hmac_secret:
    file: ./secrets/authelia_hmac_secret
  authelia_oidc_issuer_private_key:
    file: ./secrets/authelia_oidc_issuer_private_key
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_password:
    file: ./secrets/mysql_password
  cf_email:
    file: ./secrets/cf_email
  cf_api_key:
    file: ./secrets/cf_api_key
