version: "3.9"

services:
  traefik-proxy:
    extends:
      file: docker-compose.base.yml
      service: traefik-proxy

  socket-proxy:
    extends:
      file: docker-compose.base.yml
      service: socket-proxy

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis


#-----------
# Networks
#-----------
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge
