version: "3.9"

services:
  traefik-proxy:
    image: traefik:2.10
    restart: always
    depends_on:
      - socket-proxy
    networks:
      - traefik-internal
      - traefik-proxy
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', 'traefik', 'healthcheck', '--ping' ]
      interval: 5s
      retries: 3
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - './lib/traefik/traefik.yml:/etc/traefik/traefik.yml:ro'   # Static Traefik Configuration
      - './lib/traefik/dynamic/:/etc/traefik/dynamic/:ro'         # Folder to store dynamic configuration file provider
      - './lib/traefik/acme/cloudflare.json:/etc/traefik/acme/cloudflare.json'    # certificate storage
      - './lib/traefik/traefik.log:/etc/traefik/traefik.log'    # traefik log
      - './lib/traefik/access.log:/etc/traefik/access.log'      # access log
      - './certs/:/etc/traefik/certs/:ro'                       # certificate storage
    environment:
      ROOT_DOMAIN_NAME: '${ROOT_DOMAIN_NAME}'
      TRAEFIK_DOMAIN_NAME: '${TRAEFIK_DOMAIN_NAME}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.http-catchall.entrypoints=http'
      - 'traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.middlewares=middlewares-https-redirect-scheme@file'
      - 'traefik.http.routers.traefik-rtr.tls=true'
      - 'traefik.http.routers.traefik-rtr.entrypoints=https'
      - 'traefik.http.routers.traefik-rtr.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)'
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
      - 'traefik.http.routers.ping.rule=Host(`${TRAEFIK_DOMAIN_NAME}`) && Path(`/ping`)'
      - 'traefik.http.routers.ping.tls=true'
      - 'traefik.http.routers.ping.service=ping@internal'

  socket-proxy:
    image: tecnativa/docker-socket-proxy:0.1.1
    restart: always
    networks:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ NONE, 'wget --spider http://localhost:2375/version || exit 1' ]
      interval: 29s
      retries: 3
      timeout: 5s
      start_period: 21s
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0
      - INFO=0
      - NETWORKS=0
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=0

  redis:
    image: redis:7.0.5-alpine
    restart: always
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - 5124mb
      - --maxmemory-policy
      - allkeys-lru
    networks:
      - traefik-internal
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

#-----------
# Networks
#-----------
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge
