version: "3.9"

services:
  traefik-proxy:
    extends:
      file: docker-compose.base.yml
      service: traefik-proxy
    command:
      - --entrypoints.https.http.tls.domains[rootDomain].main=$ROOT_DOMAIN_NAME
      - --entrypoints.https.http.tls.domains[rootDomain].sans=*.$ROOT_DOMAIN_NAME
    environment:
      CF_API_EMAIL_FILE: '/run/secrets/cf_email'
      CF_API_KEY_FILE: '/run/secrets/cf_api_key'
    secrets:
      - cf_email
      - cf_api_key
    labels:
      - 'traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare'

  socket-proxy:
    extends:
      file: docker-compose.base.yml
      service: socket-proxy

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

#-----------
# Networks
#-----------
networks:
  traefik-internal:
    name: traefik-internal
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge

#-----------
# Secrets
#-----------
secrets:
  cf_email:
    file: ./secrets/cf_email
  cf_api_key:
    file: ./secrets/cf_api_key
