server:
    host: 0.0.0.0
    port: 9091
log:
    level: warn
    file_path: /config/authelia.log
    keep_stdout: true
# ToDo: Replace domain
default_redirection_url: https://authelia.local.dev
ntp:
    address: time.cloudflare.com:123
    version: 3
    max_desync: 3s
    disable_startup_check: false
    disable_failure: false
totp:
    disable: false
    issuer: authelia.com
    algorithm: sha1
    digits: 6
    period: 30
    skew: 1
    secret_size: 32
webauthn:
    disable: false
    display_name: Authelia Traefik
    attestation_conveyance_preference: indirect
    user_verification: preferred
    timeout: 60s
authentication_backend:
    password_reset:
        disable: false
    file:
        path: /config/users_database.yml
        password:
            algorithm: argon2id
            iterations: 3
            key_length: 32
            salt_length: 16
            parallelism: 4
            memory: 1024
access_control:
    default_policy: deny
    rules:
        - domain:
            # ToDo: Replace domain
            - authelia.local.dev
          policy: bypass
          subject: []
        - domain:
            - local.dev
          policy: one_factor
          subject: []
        - domain:
            # ToDo: Replace domain
            - traefik.local.dev
          policy: two_factor
          subject:
            - group:admins
            - group:traefik
session:
    redis:
        host: redis
        port: 6379
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0
    name: authelia_session
    expiration: 3600
    inactivity: 300
    domain: local.dev
regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 5m
password_policy:
    standard:
        enabled: true
        min_length: 8
        max_length: 0
        require_uppercase: true
        require_lowercase: true
        require_number: true
        require_special: false
storage:
    mysql:
        host: mariadb
        port: 3306
        database: authelia
        username: authelia
notifier:
    disable_startup_check: false
#    smtp:
#        username: noreply@local.dev
#        host: smtp.local.dev
#        port: 465
#        sender: Authelia <noreply@local.dev>
#        subject: '[Authelia] {title}'
#        startup_check_address: noreply@local.dev
